### ISSUE TITLE
空调当前温度显示为102.5度

### ISSUE THREAD

**Issue by lioekas** [mac-zhou/midea-ac-py#1]
空调当前温度显示为102.5度
在美的美居里面显示是正常的（室外:24度 室内:25度）

**Comment by mac-zhou** [comment]
请贴截图

**Comment by mac-zhou** [comment]
并且贴一下HA 60s内的详细log

**Comment by KIMterry86** [comment]
我也有类似的问题. 户外温度显示为102.5度。然后有时候当前温度跳到-25度。

![image](https://user-images.githubusercontent.com/59163709/81887356-7f05a000-95d1-11ea-8467-5e2fa226f62f.png)

![image](https://user-images.githubusercontent.com/59163709/81887213-3352f680-95d1-11ea-9a50-b7c462b43401.png)
日志详细信息（ ERROR ）
Logger: homeassistant.helpers.entity
Source: custom_components/midea/climate.py:108
First occurred: 2020年5月13日 下午10:13:08 (6 occurrences)
Last logged: 上午8:40:20

Update for climate.midea_df6401000033 fails
Update for climate.midea_6d2100000041 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in async_device_update
    await self.async_update()
  File "/config/custom_components/midea/climate.py", line 108, in async_update
    await self.hass.async_add_executor_job(self._device.refresh)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/msmart/device.py", line 170, in refresh
    data = self._lan_service.appliance_transparent_send(data)
  File "/usr/local/lib/python3.7/site-packages/msmart/lan.py", line 63, in appliance_transparent_send
    response = bytearray(self.request(data))[40:88]
  File "/usr/local/lib/python3.7/site-packages/msmart/lan.py", line 38, in request
    response = sock.recv(256)
socket.timeout: timed out

**Comment by BH4WHN** [comment]
我也出现零下-25度的问题，但未出现+100多度的情况

**Comment by mac-zhou** [comment]
当前温度出现异常，主要应该是解析室外温度出现异常或者返回数据异常

**Comment by mac-zhou** [comment]
请升级最新版本，或者直接修改manifest.json中```msmart==0.1.13```
ha的配置中增加:
```
logger:
  default: info
  logs:
    custom_components.midea: debug
    msmart: debug
```
再有相关问题 请筛选出相关log反馈过来

**Comment by mac-zhou** [comment]
升级msmart到0.1.15试试，我暂时没在这里升级
直接改custom_components/midea_ac/manifest.json

**Comment by mac-zhou** [comment]
新版本已经修复
