### ISSUE TITLE
midea-discover issues

### ISSUE THREAD

**Issue by Gtasian** [mac-zhou/midea-ac-py#112]
**Describe the bug （描述一下问题）**
I'm not able to run midea-discover command properly. If I use "pip3 install msmart" and then "midea-discover", I get the following.

pi@raspberrypi:~ $ midea-discover
Traceback (most recent call last):
  File "/home/pi/.local/bin/midea-discover", line 6, in <module>
    from msmart.cli import discover
  File "/home/pi/.local/lib/python3.7/site-packages/msmart/cli.py", line 8, in <module>
    from msmart.scanner import MideaDiscovery
  File "/home/pi/.local/lib/python3.7/site-packages/msmart/scanner.py", line 8, in <module>
    from msmart.cloud import cloud
  File "/home/pi/.local/lib/python3.7/site-packages/msmart/cloud.py", line 8, in <module>
    from msmart.security import security
  File "/home/pi/.local/lib/python3.7/site-packages/msmart/security.py", line 5, in <module>
    from Cryptodome.Util.Padding import pad, unpad
ImportError: cannot import name 'pad' from 'Cryptodome.Util.Padding' (/home/pi/.local/lib/python3.7/site-packages/Cryptodome/Util/Padding.py

If I use "sudo pip3 install msmart" and "sudo midea-discover", then it comes back as expected with the AC unit info but will not connect in HomeAssistant still. 

**Versions (版本信息)**
 - Home Assistant version: 2021.11.3
 - Midea msmart version: 0.1.35

**Comment by mac-zhou** [comment]
try `pip3 install pycryptodome` to fix

**Comment by Gtasian** [comment]
I'm still getting the same error

pi@raspberrypi:~ $ pip3 install msmart
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting msmart
  Using cached https://files.pythonhosted.org/packages/b7/00/83f78527d4be4fa0eba68c4e614368357fe1e9c7cb3451e6bb1f7f3bdfc2/msmart-0.2.0-py3-none-any.whl
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from msmart) (2.21.0)
Requirement already satisfied: click in /usr/lib/python3/dist-packages (from msmart) (7.0)
Requirement already satisfied: pycryptodomex in ./.local/lib/python3.7/site-packages (from msmart) (3.11.0)
Requirement already satisfied: ifaddr in ./.local/lib/python3.7/site-packages (from msmart) (0.1.7)
Installing collected packages: msmart
Successfully installed msmart-0.2.0

pi@raspberrypi:~ $ midea-discover
Traceback (most recent call last):
  File "/home/pi/.local/bin/midea-discover", line 6, in <module>
    from msmart.cli import discover
  File "/home/pi/.local/lib/python3.7/site-packages/msmart/cli.py", line 8, in <module>
    from msmart.scanner import MideaDiscovery
  File "/home/pi/.local/lib/python3.7/site-packages/msmart/scanner.py", line 9, in <module>
    from msmart.cloud import cloud
  File "/home/pi/.local/lib/python3.7/site-packages/msmart/cloud.py", line 8, in <module>
    from msmart.security import security
  File "/home/pi/.local/lib/python3.7/site-packages/msmart/security.py", line 5, in <module>
    from Cryptodome.Util.Padding import pad, unpad
ImportError: cannot import name 'pad' from 'Cryptodome.Util.Padding' (/home/pi/.local/lib/python3.7/site-packages/Cryptodome/Util/Padding.py)

pi@raspberrypi:~ $ pip3 install pycryptodome
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pycryptodome
  Using cached https://www.piwheels.org/simple/pycryptodome/pycryptodome-3.12.0-cp35-abi3-linux_armv7l.whl
Installing collected packages: pycryptodome
Successfully installed pycryptodome-3.12.0

pi@raspberrypi:~ $ midea-discover
Traceback (most recent call last):
  File "/home/pi/.local/bin/midea-discover", line 6, in <module>
    from msmart.cli import discover
  File "/home/pi/.local/lib/python3.7/site-packages/msmart/cli.py", line 8, in <module>
    from msmart.scanner import MideaDiscovery
  File "/home/pi/.local/lib/python3.7/site-packages/msmart/scanner.py", line 9, in <module>
    from msmart.cloud import cloud
  File "/home/pi/.local/lib/python3.7/site-packages/msmart/cloud.py", line 8, in <module>
    from msmart.security import security
  File "/home/pi/.local/lib/python3.7/site-packages/msmart/security.py", line 5, in <module>
    from Cryptodome.Util.Padding import pad, unpad
ImportError: cannot import name 'pad' from 'Cryptodome.Util.Padding' (/home/pi/.local/lib/python3.7/site-packages/Cryptodome/Util/Padding.py)

**Comment by mac-zhou** [comment]
> 
> If I use "sudo pip3 install msmart" and "sudo midea-discover", then it comes back as expected with the AC unit info but will not connect in HomeAssistant still.
> 
HomeAssistant don't use midea-discover.
add the AC to your HomeAssistant , then show me the HomeAssistant's log
