### ISSUE TITLE
Dehumidifer Support

### ISSUE THREAD

**Issue by jchasey** [mac-zhou/midea-ac-py#12]
**Describe the bug （描述一下问题）**

Currently dehumidifer like  EVA II PRO WiFi Smart Dehumidifier are not working, although the Midea Air application works with them just fine.

The following error occurs when the integration starts:

I also noticed that in the library for the device type for a dehumidifer you have code 0x00 when it should be 0xA1

**Screenshots / Logs / Pcap File（屏幕截图/日志/抓包文件）**

Logger: homeassistant.helpers.entity
Source: custom_components/midea_ac/climate.py:108
First occurred: 11:16:32 AM (205 occurrences)
Last logged: 12:10:40 PM

Update for climate.midea_ac_e42300000011 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in async_device_update
    await self.async_update()
  File "/config/custom_components/midea_ac/climate.py", line 108, in async_update
    await self.hass.async_add_executor_job(self._device.refresh)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/msmart/device.py", line 173, in refresh
    data = self._lan_service.appliance_transparent_send(data)
  File "/usr/local/lib/python3.7/site-packages/msmart/lan.py", line 69, in appliance_transparent_send
    response = bytearray(self.request(data))[40:88]
TypeError: 'NoneType' object is not iterable

**Versions (版本信息)**
 - Home Assistant version: 0.110.2
 - Midea msmart version: 0.1.13

**Comment by mac-zhou** [comment]
this just support 0xAC model device.
what is your model in Midea, i known Dehumidifer's model is 0xCC in midea.
please check your device's model

**Comment by mac-zhou** [comment]
change msmart == 0.1.15 in custom_components/midea_ac/manifest.json file and restart HASS
after try to control
