### ISSUE TITLE
ACs don't connect 

### ISSUE THREAD

**Issue by rdanika** [mac-zhou/midea-ac-py#121]
I have 5 midea AC in my home. I connected one succesfully. I did everything the same way but the rest come back with error msg.

This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/midea_ac/climate.py:129
Integration: midea_ac (documentation)
First occurred: 12:14:22 AM (16 occurrences)
Last logged: 12:18:07 AM

Update for climate.midea_ac_19791209335051 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 691, in async_device_update
    raise exc
  File "/config/custom_components/midea_ac/climate.py", line 129, in async_update
    await self.hass.async_add_executor_job(self._device.apply)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/msmart/device.py", line 264, in apply
    self._send_cmd(cmd)
  File "/usr/local/lib/python3.9/site-packages/msmart/device.py", line 208, in _send_cmd
    responses = self._lan_service.appliance_transparent_send_8370(data)
  File "/usr/local/lib/python3.9/site-packages/msmart/lan.py", line 136, in appliance_transparent_send_8370
    data = self.security.encode_8370(data, msgtype)
  File "/usr/local/lib/python3.9/site-packages/msmart/security.py", line 120, in encode_8370
    data = self.aes_cbc_encrypt(data, self._tcp_key) + sign
  File "/usr/local/lib/python3.9/site-packages/msmart/security.py", line 57, in aes_cbc_encrypt
    return AES.new(key, AES.MODE_CBC, iv=self.iv).encrypt(raw)
  File "/usr/local/lib/python3.9/site-packages/Cryptodome/Cipher/AES.py", line 232, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/Cryptodome/Cipher/__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/Cryptodome/Cipher/_mode_cbc.py", line 274, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "/usr/local/lib/python3.9/site-packages/Cryptodome/Cipher/AES.py", line 92, in _create_base_cipher
    if len(key) not in key_size:
TypeError: object of type 'NoneType' has no len()

Logger: msmart.lan
Source: /usr/local/lib/python3.9/site-packages/msmart/lan.py:43
First occurred: 12:29:37 AM (14 occurrences)
Last logged: 12:30:17 AM

Connect Error: 192.168.1.170:6444 timed out
Connect Error: 192.168.1.118:6444 timed out
Connect Error: 192.168.1.69:6444 timed out
Connect Error: 192.168.1.49:6444 timed out
Connect Error: 192.168.1.69:6444 [Errno 9] Bad file descriptor

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/midea_ac/climate.py:120
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:30:15 AM (2 occurrences)
Last logged: 12:30:16 AM

[140681262853520] object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 586, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/config/custom_components/midea_ac/climate.py", line 269, in async_set_temperature
    await self.apply_changes()
  File "/config/custom_components/midea_ac/climate.py", line 120, in apply_changes
    await self.hass.async_add_executor_job(self._device.apply)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/msmart/device.py", line 264, in apply
    self._send_cmd(cmd)
  File "/usr/local/lib/python3.9/site-packages/msmart/device.py", line 208, in _send_cmd
    responses = self._lan_service.appliance_transparent_send_8370(data)
  File "/usr/local/lib/python3.9/site-packages/msmart/lan.py", line 136, in appliance_transparent_send_8370
    data = self.security.encode_8370(data, msgtype)
  File "/usr/local/lib/python3.9/site-packages/msmart/security.py", line 120, in encode_8370
    data = self.aes_cbc_encrypt(data, self._tcp_key) + sign
  File "/usr/local/lib/python3.9/site-packages/msmart/security.py", line 57, in aes_cbc_encrypt
    return AES.new(key, AES.MODE_CBC, iv=self.iv).encrypt(raw)
  File "/usr/local/lib/python3.9/site-packages/Cryptodome/Cipher/AES.py", line 232, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/Cryptodome/Cipher/__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/Cryptodome/Cipher/_mode_cbc.py", line 274, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "/usr/local/lib/python3.9/site-packages/Cryptodome/Cipher/AES.py", line 92, in _create_base_cipher
    if len(key) not in key_size:
TypeError: object of type 'NoneType' has no len()

**Comment by mac-zhou** [comment]
5 midea  use same token and key?

**Comment by rdanika** [comment]
I don't think so. Those are the same network and connected to the cloud trough on my account, but all have own wifi stick. The midea discover come back with different Tokens and Keys

**Comment by rdanika** [comment]
Output of the midea-discover:

INFO:msmart.cli:*** Found a device: ←[94m←[1m{'type': 'ac', 'support': True, 'version': 3, 'ip': '192.168.0.49', 'id': 18691697789245, 'port': 6444, 'token': '96A80914CCE4B5B6A68F1CEB610658724F3AD852DEF83B0E2F50B1EDEBEEBDEE2DAC473EFA79E677AE273D29E022CECDE4DD415DA40BB0E875C2B61105C51C05', 'key': 'E9809F0A85B441F18ECBADB58CB644C802BB9680BD5447BEA1520B874F5A0225', 'ssid': 'net_ac_8991'} ←[0m
INFO:msmart.cli:*** Found a device: ←[94m←[1m{'type': 'ac', 'support': True, 'version': 3, 'ip': '192.168.0.69', 'id': 19791209335051, 'port': 6444, 'token': 'A713416C1E0692F50E9723927585713986D9577CD327795B3E93FA87B1482C0701E036303BA4BA03F554FA42AF8A3D1E4640205D31DD21125DB75E8886961F75', 'key': 'A06E367E19454ECD9C58FF57260F5911406214ACA46D43698414B0234D064C9B', 'ssid': 'net_ac_EF9E'} ←[0m
INFO:msmart.cli:*** Found a device: ←[94m←[1m{'type': 'ac', 'support': True, 'version': 3, 'ip': '192.168.0.118', 'id': 20890720964296, 'port': 6444, 'token': '2F3108B04294ED22ACB62D1F4EBBCDD00C5FA4FEB397E4BAE7F7CB48EF0AF5C8DD27AB2E2EE2EFC8237BDF98B8CEB2A4351FE167E30925DDC2A30E63BC3E2D82', 'key': 'EDF56F52A8314FA6BCC213576E2E854340462D0AC0AB42A584E1156D074B8282', 'ssid': 'net_ac_9388'} ←[0m
INFO:msmart.cli:*** Found a device: ←[94m←[1m{'type': 'ac', 'support': True, 'version': 3, 'ip': '192.168.0.188', 'id': 18691697839631, 'port': 6444, 'token': 'CEEE13EE5618E0A9B6191B926301F2B34855A6917CA5310BE28590830F02F241335C32EFA869567711FE21930A8972888057F3AF1D13F5CAC5F95AA7B3D28E1A', 'key': 'B269CB9F6CA447F082102D4CD275B526389E9784D0A846AA81936951C7AD3286', 'ssid': 'net_ac_83D2'} ←[0m
INFO:msmart.cli:*** Found a device: ←[94m←[1m{'type': 'ac', 'support': True, 'version': 3, 'ip': '192.168.0.170', 'id': 19791209335186, 'port': 6444, 'token': 'A0D4E31DD52E481EB65AFF8E8241445175B0E043DCF7000758BC4461109CDD1691CD4C37029B730289257F86CFB529735C3291E99A147CFD42F66D8BCB515B77', 'key': '384DFE21DEC7405DA7BAA0FF9866A84C139EEAE10CC443B6806CEB12E9E774B2', 'ssid': 'net_ac_40D1'} ←[0m

**Comment by mac-zhou** [comment]
please update new version, If there are still problems, send me the file `home-assistant.log`
join the telegram group (https://t.me/+UFSSaqBJE5RqvSOq), you can find me.

**Comment by KhArtNJava** [comment]
Any news on this question? I've same issue.

**Comment by mac-zhou** [comment]
The new version(v0.2.2) should solve this problem, please update
