### ISSUE TITLE
无法用我的美的美居app账号登录获取token和k1

### ISSUE THREAD

**Issue by huiyanga** [mac-zhou/midea-ac-py#127]
PS D:\py3.9\Scripts> midea-discover -a 159xxxxxxxxx -p xxxxxxxxxx
INFO:msmart.cli:msmart version: 0.2.0 Currently only supports ac devices.
Traceback (most recent call last):
  File "d:\py3.9\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\py3.9\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\py3.9\Scripts\midea-discover.exe\__main__.py", line 7, in <module>
  File "d:\py3.9\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "d:\py3.9\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "d:\py3.9\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\py3.9\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "d:\py3.9\lib\site-packages\msmart\cli.py", line 45, in discover
    found_devices = loop.run_until_complete(discovery.get_all() if ip == '' else discovery.get(ip))
  File "d:\py3.9\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "d:\py3.9\lib\site-packages\msmart\scanner.py", line 181, in get_all
    await self._process_tasks(tasks)
  File "d:\py3.9\lib\site-packages\msmart\scanner.py", line 187, in _process_tasks
    [self.result.add(task.result()) for task in tasks]
  File "d:\py3.9\lib\site-packages\msmart\scanner.py", line 187, in <listcomp>
    [self.result.add(task.result()) for task in tasks]
  File "d:\py3.9\lib\site-packages\msmart\scanner.py", line 44, in support_test
    _device = await self.support_testv3(account, password)
  File "d:\py3.9\lib\site-packages\msmart\scanner.py", line 59, in support_testv3
    token, key = await loop.run_in_executor(None, gettoken, udpid, account, password)
  File "d:\py3.9\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\py3.9\lib\site-packages\msmart\scanner.py", line 242, in gettoken
    Client.login()
  File "d:\py3.9\lib\site-packages\msmart\cloud.py", line 112, in login
    self.get_login_id()
  File "d:\py3.9\lib\site-packages\msmart\cloud.py", line 102, in get_login_id
    response = self.api_request("user/login/id/get", {
  File "d:\py3.9\lib\site-packages\msmart\cloud.py", line 86, in api_request
    self.handle_api_error(int(response['errorCode']), response['msg'])
  File "d:\py3.9\lib\site-packages\msmart\cloud.py", line 233, in handle_api_error
    handler()
  File "d:\py3.9\lib\site-packages\msmart\cloud.py", line 219, in throw
    raise ValueError(error_code, message)
ValueError: (3102, 'this account does not exist')
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-2' coro=<scandevice.support_test() done, defined at d:\py3.9\lib\site-packages\msmart\scanner.py:42> exception=ValueError(3102, 'this account does not exist')>
Traceback (most recent call last):
  File "d:\py3.9\lib\site-packages\msmart\scanner.py", line 44, in support_test
    _device = await self.support_testv3(account, password)
  File "d:\py3.9\lib\site-packages\msmart\scanner.py", line 59, in support_testv3
    token, key = await loop.run_in_executor(None, gettoken, udpid, account, password)
  File "d:\py3.9\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "d:\py3.9\lib\site-packages\msmart\scanner.py", line 242, in gettoken
    Client.login()
  File "d:\py3.9\lib\site-packages\msmart\cloud.py", line 112, in login
    self.get_login_id()
  File "d:\py3.9\lib\site-packages\msmart\cloud.py", line 102, in get_login_id
    response = self.api_request("user/login/id/get", {
  File "d:\py3.9\lib\site-packages\msmart\cloud.py", line 86, in api_request
    self.handle_api_error(int(response['errorCode']), response['msg'])
  File "d:\py3.9\lib\site-packages\msmart\cloud.py", line 233, in handle_api_error
    handler()
  File "d:\py3.9\lib\site-packages\msmart\cloud.py", line 219, in throw
    raise ValueError(error_code, message)
ValueError: (3102, 'this account does not exist')

**Comment by mac-zhou** [comment]
`midea-discover` use a registered account of Midea Air APP [[AppStore]](https://apps.apple.com/app/midea-air/id1007999530) [[GooglePlay]](https://play.google.com/store/apps/details?id=com.midea.aircondition.obm) to get Token and K1(key).

不支持国内的美的美居的账号，请注册国外版本Midea Air APP 不需要添加设备，只需要注册
或者你直接使用内置的账号即可
