### ISSUE TITLE
经常报'NoneType' object is not iterable

### ISSUE THREAD

**Issue by pydog** [mac-zhou/midea-ac-py#14]
TypeError: 'NoneType' object is not iterable
2020-05-28 16:36:08 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.childrenroom_aircondition fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in async_device_update
    await self.async_update()
  File "/config/custom_components/midea/climate.py", line 108, in async_update
    await self.hass.async_add_executor_job(self._device.refresh)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/msmart/device.py", line 173, in refresh
    data = self._lan_service.appliance_transparent_send(data)
  File "/usr/local/lib/python3.7/site-packages/msmart/lan.py", line 69, in appliance_transparent_send
    response = bytearray(self.request(data))[40:88]
TypeError: 'NoneType' object is not iterable

**Comment by mac-zhou** [comment]
升级msmart到0.1.15，我暂时没在这里升级
直接改custom_components/midea_ac/manifest.json

**Comment by pydog** [comment]
大佬回复太及时了，马上改完测试
