### ISSUE TITLE
homeassistant.exceptions.Unauthorized: Unauthorized

### ISSUE THREAD

**Issue by Cireasa23** [mac-zhou/midea-ac-py#15]
Logger: homeassistant.components.websocket_api.http.connection.178689
Source: helpers/service.py:514
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 6:56:48 PM (1 occurrences)
Last logged: 6:56:48 PM

Unauthorized
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1288, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 514, in admin_handler
    raise Unauthorized(context=call.context)
homeassistant.exceptions.Unauthorized: Unauthorized

**Comment by mac-zhou** [comment]
this is not the problem with midea_ac components
