### ISSUE TITLE
经常update失败

### ISSUE THREAD

**Issue by pydog** [mac-zhou/midea-ac-py#16]
ha 的log里面经常出现更新超时，有可能是什么原因导致的？
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in async_device_update
    await self.async_update()
  File "/config/custom_components/midea/climate.py", line 108, in async_update
    await self.hass.async_add_executor_job(self._device.refresh)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/msmart/device.py", line 171, in refresh
    data = self._lan_service.appliance_transparent_send(data)
  File "/usr/local/lib/python3.7/site-packages/msmart/lan.py", line 69, in appliance_transparent_send
    response = bytearray(self.request(data))
  File "/usr/local/lib/python3.7/site-packages/msmart/lan.py", line 33, in request
    sock.connect(device_address)
socket.timeout: timed out
2020-05-30 22:14:50 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.primaryroom_aircondition is taking over 10 seconds
2020-05-30 22:14:50 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.primaryroom_aircondition fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in async_device_update
    await self.async_update()
  File "/config/custom_components/midea/climate.py", line 108, in async_update
    await self.hass.async_add_executor_job(self._device.refresh)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/msmart/device.py", line 171, in refresh
    data = self._lan_service.appliance_transparent_send(data)
  File "/usr/local/lib/python3.7/site-packages/msmart/lan.py", line 69, in appliance_transparent_send
    response = bytearray(self.request(data))
  File "/usr/local/lib/python3.7/site-packages/msmart/lan.py", line 33, in request
    sock.connect(device_address)
socket.timeout: timed out

**Comment by pydog** [comment]
UDP有这么不稳定吗？我的opple灯也是，app控制很稳定，接入ha就经常显示离线
