### ISSUE TITLE
Will not give me the info

### ISSUE THREAD

**Issue by fsmc1974** [mac-zhou/midea-ac-py#162]
**Describe the bug （描述一下问题）**
Trying to get AC info and I get the following errors

**Screenshots / Logs / Pcap File（屏幕截图/日志/抓包文件）**
INFO:msmart.cli:msmart version: 0.2.3 Currently only supports ac devices, only support MSmartHome APP.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f5aefca65b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='mp-prod.appsmb.com', port=443): Max retries exceeded with url: /mas/v5/app/proxy?alias=/v1/user/login/id/get (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5aefca65b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/administrator/.local/bin/midea-discover", line 8, in <module>
    sys.exit(discover())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/administrator/.local/lib/python3.8/site-packages/msmart/cli.py", line 45, in discover
    found_devices = loop.run_until_complete(discovery.get_all() if ip == '' else discovery.get(ip))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/administrator/.local/lib/python3.8/site-packages/msmart/scanner.py", line 193, in get_all
    await self._process_tasks(tasks)
  File "/home/administrator/.local/lib/python3.8/site-packages/msmart/scanner.py", line 199, in _process_tasks
    [self.result.add(task.result()) for task in tasks]
  File "/home/administrator/.local/lib/python3.8/site-packages/msmart/scanner.py", line 199, in <listcomp>
    [self.result.add(task.result()) for task in tasks]
  File "/home/administrator/.local/lib/python3.8/site-packages/msmart/scanner.py", line 50, in support_test
    _device = await self.support_testv3(account, password)
  File "/home/administrator/.local/lib/python3.8/site-packages/msmart/scanner.py", line 65, in support_testv3
    token, key = await loop.run_in_executor(None, gettoken, udpid, account, password)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/administrator/.local/lib/python3.8/site-packages/msmart/scanner.py", line 255, in gettoken
    Client.login()
  File "/home/administrator/.local/lib/python3.8/site-packages/msmart/cloud.py", line 136, in login
    self.get_login_id()
  File "/home/administrator/.local/lib/python3.8/site-packages/msmart/cloud.py", line 125, in get_login_id
    response = self.api_request(
  File "/home/administrator/.local/lib/python3.8/site-packages/msmart/cloud.py", line 96, in api_request
    r = requests.post(
  File "/usr/lib/python3/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='mp-prod.appsmb.com', port=443): Max retries exceeded with url: /mas/v5/app/proxy?alias=/v1/user/login/id/get (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5aefca65b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

**Versions (版本信息)**
 - Home Assistant version: 
 - Midea msmart version:

**Comment by mill1000** [comment]
Can your system access the internet? It looks like a failure in DNS resolution.
