### ISSUE TITLE
添加之后提示[Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by sadgen** [mac-zhou/midea-ac-py#19]
**Describe the bug （描述一下问题）**
添加之后提示[Errno 104] Connection reset by peer

**Screenshots / Logs / Pcap File（屏幕截图/日志/抓包文件）**
Logger: homeassistant.components.websocket_api.http.connection.140300961035472
Source: custom_components/midea_ac/climate.py:95
Integration: websocket_api (documentation, issues)
First occurred: 下午12:24:23 (5 occurrences)
Last logged: 下午12:24:38

[Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1232, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1255, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 412, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 600, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 443, in _handle_entity_call
    await result
  File "/config/custom_components/midea_ac/climate.py", line 263, in async_set_hvac_mode
    await self.apply_changes()
  File "/config/custom_components/midea_ac/climate.py", line 95, in apply_changes
    await self.hass.async_add_executor_job(self._device.apply)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/msmart/device.py", line 197, in apply
    data = self._lan_service.appliance_transparent_send(data)
  File "/usr/local/lib/python3.7/site-packages/msmart/lan.py", line 69, in appliance_transparent_send
    response = bytearray(self.request(data))[40:88]
  File "/usr/local/lib/python3.7/site-packages/msmart/lan.py", line 41, in request
    response = sock.recv(512)
ConnectionResetError: [Errno 104] Connection reset by peer
**Versions (版本信息)**
 - Home Assistant version: 0.108.0
 - Midea msmart version: 0.1.15

**Comment by mac-zhou** [comment]
升级一下
- 你可以在同一网络下的设备上运行 midea-discover 命令去发现相关midea的设备。注意：插件仅支持型号为0xac(空调)且输出中有 ```supported``` 字样的设备。
```shell
pip3 install msmart
midea-discover
```
