### ISSUE TITLE
ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.midea_ac_xxbx00000010 fails

### ISSUE THREAD

**Issue by Asom-Velz** [mac-zhou/midea-ac-py#25]
**Describe the bug （描述一下问题）**
I have this error ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.midea_ac_xxbx00000010 fails 
ValueError: byte must be in range(0, 256)

**Screenshots / Logs / Pcap File（屏幕截图/日志/抓包文件）**
If applicable, add screenshots or your home-assistant log file or pcap file to help explain your problem.
请提交相关截图，日志，抓包让开发者能够更快的解决问题
2020-06-16 10:11:29 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.midea_ac_xxbx00000010 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in async_device_update
    await self.async_update()
  File "/config/custom_components/midea_ac/climate.py", line 108, in async_update
    await self.hass.async_add_executor_job(self._device.refresh)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/msmart/device.py", line 178, in refresh
    data = pkt_builder.finalize()
  File "/usr/local/lib/python3.7/site-packages/msmart/packet_builder.py", line 46, in finalize
    self.command.append(self.checksum(self.command[1:]))
ValueError: byte must be in range(0, 256)
2020-06-16 10:21:29 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.midea_ac_xxbx00000010 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in async_device_update
    await self.async_update()
  File "/config/custom_components/midea_ac/climate.py", line 108, in async_update
    await self.hass.async_add_executor_job(self._device.refresh)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/msmart/device.py", line 178, in refresh
    data = pkt_builder.finalize()
  File "/usr/local/lib/python3.7/site-packages/msmart/packet_builder.py", line 46, in finalize
    self.command.append(self.checksum(self.command[1:]))
ValueError: byte must be in range(0, 256)

**Versions (版本信息)**
 - Home Assistant version: Home Assistant 0.111.3 System | HassOS 4.10
 - Midea msmart version: 35ed4a3

**Comment by mac-zhou** [comment]
next msmart version will fix this bug
or you can change File "/usr/local/lib/python3.7/site-packages/msmart/packet_builder.py", line 61:
```return (~ sum(data) + 1) & 0xff```

**Comment by javierdc** [comment]
Seems I don't have that file, under /usr/local/lib/python3.7/ I only see dst_packages and does not contain the file mentioned above. Thanks

**Comment by mac-zhou** [comment]
> Seems I don't have that file, under /usr/local/lib/python3.7/ I only see dst_packages and does not contain the file mentioned above. Thanks

Then you wait for the update

**Comment by aa755** [comment]
to find the location of the file, you can do `sudo updatedb; locate packet_builder.py`

**Comment by javierdc** [comment]
Just installed the updated version and now it is working fine. Thanks!

**Comment by mac-zhou** [comment]
new version 0.1.19 fix this bug
