### ISSUE TITLE
After upgrade

### ISSUE THREAD

**Issue by cyberfly79** [mac-zhou/midea-ac-py#31]
After the update, this error is reported:
(core in docker:  0.109.6)

ERROR (MainThread) [homeassistant.components.climate] Error while setting up midea_ac platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/midea_ac/climate.py", line 65, in async_setup_platform
    client = midea_device(device_ip, int(device_id), device_port)
TypeError: __init__() takes 3 positional arguments but 4 were given

**Comment by mac-zhou** [comment]
if there is a problem, please reopen this issues.
