### ISSUE TITLE
Authentication Error with fake cloud

### ISSUE THREAD

**Issue by fraschizzato** [mac-zhou/midea-ac-py#35]
**Describe the bug （描述一下问题）**
I get Authentication Failed in HA logs and so components its not initialized

**Screenshots / Logs / Pcap File（屏幕截图/日志/抓包文件）**
Logger: homeassistant.components.climate
Source: custom_components/midea_ac/climate.py:73
Integration: Termostato (documentation, issues)
First occurred: 22:24:19 (1 occurrences)
Last logged: 22:24:19

Error while setting up midea_ac platform for climate
Traceback (most recent call last):
  File "/home/pi/hassmar20/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/home/pi/.homeassistant/custom_components/midea_ac/climate.py", line 73, in async_setup_platform
    device.authenticate(device_8370_only_ac_mac, device_8370_only_wifi_ssid, device_8370_only_wifi_pw)
  File "/home/pi/hassmar20/lib/python3.7/site-packages/msmart/device.py", line 43, in authenticate
    self._authenticate()
  File "/home/pi/hassmar20/lib/python3.7/site-packages/msmart/device.py", line 46, in _authenticate
    self._lan_service.authenticate(self._mac, self._wifi_ssid, self._wifi_pw)
  File "/home/pi/hassmar20/lib/python3.7/site-packages/msmart/lan.py", line 68, in authenticate
    self._authenticate()
  File "/home/pi/hassmar20/lib/python3.7/site-packages/msmart/lan.py", line 80, in _authenticate
    raise error
  File "/home/pi/hassmar20/lib/python3.7/site-packages/msmart/lan.py", line 76, in _authenticate
    tcp_key = self.security.tcp_key(response, self._key)
  File "/home/pi/hassmar20/lib/python3.7/site-packages/msmart/security.py", line 90, in tcp_key
    raise Exception('authentication failed')
Exception: authentication failed

**Versions (版本信息)**
 - Home Assistant version: 0.115.6
 - Midea msmart version:  0.1.20 (support-8370 version)

**Comment by fraschizzato** [comment]
It was a dnsmasq problem. apparently the ac had continued to resolve the real dns for some time...
