### ISSUE TITLE
无法更新设备信息，也无法控制。报错：Update for climate.midea_dd4004000086 fails

### ISSUE THREAD

**Issue by xia0linz1** [mac-zhou/midea-ac-py#5]
HA版本0.109.1，空调美的风语者KFR-35GW/BP3DN8Y-FA200
可以正常接入美的APP，美的APP可以控制
通过iPhone提取15位Applianceid，接入HA

HA报错：Update for climate.midea_dd4004000086 fails
无法读取空调状态，无法控制空调

日志如下：

> Update for climate.midea_dd4004000086 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in async_device_update
    await self.async_update()
  File "/config/custom_components/midea/climate.py", line 108, in async_update
    await self.hass.async_add_executor_job(self._device.refresh)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/msmart/device.py", line 170, in refresh
    data = self._lan_service.appliance_transparent_send(data)
  File "/usr/local/lib/python3.7/site-packages/msmart/lan.py", line 63, in appliance_transparent_send
    response = bytearray(self.request(data))[40:88]
  File "/usr/local/lib/python3.7/site-packages/msmart/lan.py", line 38, in request
    response = sock.recv(256)
socket.timeout: timed out

**Comment by xia0linz1** [comment]
今天用米家APP和小度app都试了下，米家里通用的美的wifi空调控制直接添加失败（销售宣称是可以），小度通过绑定美的云可以实现WiFi控制。
我猜测是美的从某一时刻起，更换了自己空调的wifi模块和通信协议，封堵了LAN控制的“漏洞”吧（其实这个在说明书上也有体现，提供了两个APP下载地址）
这些大厂真是一点共享精神都没，想方设法闭源自己的平台

**Comment by mac-zhou** [comment]
请升级最新版本，或者直接修改manifest.json中```msmart==0.1.13```
ha的配置中增加:
```
logger:
  default: info
  logs:
    custom_components.midea: debug
    msmart: debug
```
再有相关问题 请筛选出相关log反馈过来

**Comment by xia0linz1** [comment]
直接修改manifest.json中msmart==0.1.13，然后重启。
日志显示：2020-05-20 00:00:44 INFO (SyncWorker_18) [homeassistant.util.package] Attempting install of msmart==0.1.13
检查HA的/usr/local/lib/python3.7/site-packages/msmart下的device.py，版本已经更新至0.1.13

但是问题依旧。

相关日志如下：

```
2020-05-20 00:26:14 DEBUG (SyncWorker_14) [msmart.lan] Connect the Device 192.168.1.63:6444 TimeOut.
2020-05-20 00:26:14 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.midea_dd4004000086 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in async_device_update
    await self.async_update()
  File "/config/custom_components/midea/climate.py", line 108, in async_update
    await self.hass.async_add_executor_job(self._device.refresh)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/msmart/device.py", line 173, in refresh
    data = self._lan_service.appliance_transparent_send(data)
  File "/usr/local/lib/python3.7/site-packages/msmart/lan.py", line 69, in appliance_transparent_send
    response = bytearray(self.request(data))[40:88]
TypeError: 'NoneType' object is not iterable

2020-05-20 00:26:22 DEBUG (SyncWorker_6) [msmart.packet_builder] Finalize request data: aa20ac00000000000003410000ff03ff00020000000000000000000000000004e9
2020-05-20 00:26:22 DEBUG (SyncWorker_6) [msmart.lan] Sending to 192.168.1.63:6444 5a5a011168002000000000000000000000000000dd40040000860000000000000000000000000000c7ec8e4276f8accc266a4648044169534ef900b4addf8808145b702d1c28520aec9d938eeaae3d871b99ce4b7e20a37b799658748d6ac278f250f10414e2da38.
2020-05-20 00:26:30 DEBUG (SyncWorker_6) [msmart.lan] Connect the Device 192.168.1.63:6444 TimeOut.
2020-05-20 00:26:30 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.midea_dd4004000086 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in async_device_update
    await self.async_update()
  File "/config/custom_components/midea/climate.py", line 108, in async_update
    await self.hass.async_add_executor_job(self._device.refresh)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/msmart/device.py", line 173, in refresh
    data = self._lan_service.appliance_transparent_send(data)
  File "/usr/local/lib/python3.7/site-packages/msmart/lan.py", line 69, in appliance_transparent_send
    response = bytearray(self.request(data))[40:88]
TypeError: 'NoneType' object is not iterable

2020-05-20 00:26:37 DEBUG (SyncWorker_8) [msmart.packet_builder] Finalize request data: aa20ac00000000000003410000ff03ff00020000000000000000000000000004e9
2020-05-20 00:26:37 DEBUG (SyncWorker_8) [msmart.lan] Sending to 192.168.1.63:6444 5a5a011168002000000000000000000000000000dd40040000860000000000000000000000000000c7ec8e4276f8accc266a4648044169534ef900b4addf8808145b702d1c28520aec9d938eeaae3d871b99ce4b7e20a37b799658748d6ac278f250f10414e2da38.

2020-05-20 00:26:45 DEBUG (SyncWorker_8) [msmart.lan] Connect the Device 192.168.1.63:6444 TimeOut.
2020-05-20 00:26:45 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.midea_dd4004000086 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in async_device_update
    await self.async_update()
  File "/config/custom_components/midea/climate.py", line 108, in async_update
    await self.hass.async_add_executor_job(self._device.refresh)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/msmart/device.py", line 173, in refresh
    data = self._lan_service.appliance_transparent_send(data)
  File "/usr/local/lib/python3.7/site-packages/msmart/lan.py", line 69, in appliance_transparent_send
    response = bytearray(self.request(data))[40:88]
TypeError: 'NoneType' object is not iterable

2020-05-20 00:26:53 DEBUG (SyncWorker_5) [msmart.packet_builder] Finalize request data: aa20ac00000000000003410000ff03ff00020000000000000000000000000004e9
2020-05-20 00:26:53 DEBUG (SyncWorker_5) [msmart.lan] Sending to 192.168.1.63:6444 5a5a011168002000000000000000000000000000dd40040000860000000000000000000000000000c7ec8e4276f8accc266a4648044169534ef900b4addf8808145b702d1c28520aec9d938eeaae3d871b99ce4b7e20a37b799658748d6ac278f250f10414e2da38.
2020-05-20 00:27:01 DEBUG (SyncWorker_5) [msmart.lan] Connect the Device 192.168.1.63:6444 TimeOut.

2020-05-20 00:27:01 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.midea_dd4004000086 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in async_device_update
    await self.async_update()
  File "/config/custom_components/midea/climate.py", line 108, in async_update
    await self.hass.async_add_executor_job(self._device.refresh)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/msmart/device.py", line 173, in refresh
    data = self._lan_service.appliance_transparent_send(data)
  File "/usr/local/lib/python3.7/site-packages/msmart/lan.py", line 69, in appliance_transparent_send
    response = bytearray(self.request(data))[40:88]
TypeError: 'NoneType' object is not iterable
```

**Comment by mac-zhou** [comment]
看着目前应该是不支持你这个型号的设备了
请提供空调的抓包，在美的APP做一些操作，在路由器上抓空调进出的包，并告知操作了啥

**Comment by xia0linz1** [comment]
> 看着目前应该是不支持你这个型号的设备了
> 请提供空调的抓包，在美的APP做一些操作，在路由器上抓空调进出的包，并告知操作了啥

[midea.zip](https://github.com/mac-zhou/midea-ac-py/files/4673821/midea.zip)

抓包只包含了空调和美的云的交互，没有保留手机的相关包（安全问题，若需要我再想办法筛选出来）
大致的操作包括“开屏显-关屏显-开机（预设抽湿模式）-上下风开-上下风关-关机”

**Comment by mac-zhou** [comment]
升级新版本0.1.15 
直接改custom_components/midea_ac/manifest.json 这个文件

**Comment by xia0linz1** [comment]
升级后，先前的报错消失，但是还是不能控制。
日志报错：
Logger: homeassistant.helpers.entity
Source: __main__.py:356
First occurred: 上午11:51:19 (2 occurrences)
Last logged: 上午11:51:35

Update of climate.midea_ac_dd4004000086 is taking over 10 seconds

**Comment by mac-zhou** [comment]
是的 暂不支持你的设备 仅支持tcp头为5a5a 同时长度为104的局域网协议
 ```tcp && data.len == 104 && data[:2] == 5a5a```
