### ISSUE TITLE
After latest midea_ac update, airco cannot be connected

### ISSUE THREAD

**Issue by Dinges28** [mac-zhou/midea-ac-py#79]
**Describe the bug （描述一下问题）**
Hass cannot detect the airo anymore (timeout)
Midea app no problem
ping to internal ip adress no problem

**Screenshots / Logs / Pcap File（屏幕截图/日志/抓包文件）**
If applicable, add screenshots or your home-assistant log file or pcap file to help explain your problem.
请提交相关截图，日志，抓包让开发者能够更快的解决问题

```
2021-08-12 20:05:33 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.midea_ac_21990232557284 fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 446, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 654, in async_device_update
    raise exc
  File "/home/homeassistant/.homeassistant/custom_components/midea_ac/climate.py", line 133, in async_update
    await self.hass.async_add_executor_job(self._device.refresh)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.8/site-packages/msmart/device.py", line 195, in refresh
    self._send_cmd(cmd)
  File "/srv/homeassistant/lib/python3.8/site-packages/msmart/device.py", line 204, in _send_cmd
    responses = self._lan_service.appliance_transparent_send(data)
  File "/srv/homeassistant/lib/python3.8/site-packages/msmart/lan.py", line 102, in appliance_transparent_send
    response = self.request(data)
  File "/srv/homeassistant/lib/python3.8/site-packages/msmart/lan.py", line 42, in request
    self._connect()
  File "/srv/homeassistant/lib/python3.8/site-packages/msmart/lan.py", line 33, in _connect
    raise error
  File "/srv/homeassistant/lib/python3.8/site-packages/msmart/lan.py", line 30, in _connect
    self._socket.connect((self.device_ip, self.device_port))
socket.timeout: timed out
```

**Versions (版本信息)**
 - Home Assistant version: 2021.8.5
 - Midea msmart version: ce606c0

**Comment by Dinges28** [comment]
Downgrade of msmart to 0.1.26 gives back the device in home assistant

**Comment by mac-zhou** [comment]
Fix in the next version

**Comment by mac-zhou** [comment]
try new version msmart==0.1.29

**Comment by mstefanowicz** [comment]
@mac-zhou I have two devices with OSK-102 modules. Until 0.1.25 everything worked fine. After the update, the entities became unavailable. Below is my configuration entry. Missed something?


climate:
   - platform: midea_ac
     host: 192.168.69.160
     id: 18691697869844
     keep_last_known_online_state: true
   - platform: midea_ac
     host: 192.168.69.161
     id: 31885837308195
     keep_last_known_online_state: true

**Comment by mac-zhou** [comment]
> @mac-zhou I have two devices with OSK-102 modules. Until 0.1.25 everything worked fine. After the update, the entities became unavailable. Below is my configuration entry. Missed something?
> 
> climate:
> 
> * platform: midea_ac
>   host: 192.168.69.160
>   id: 18691697869844
>   keep_last_known_online_state: true
> * platform: midea_ac
>   host: 192.168.69.161
>   id: 31885837308195
>   keep_last_known_online_state: true

did you use the new version? 0.1.29

**Comment by mac-zhou** [comment]
and you can add to your config
```logger:
  default: info
  logs:
    custom_components.midea_ac: debug
    msmart: debug```

Happen again, please show me the log

**Comment by mstefanowicz** [comment]
> Happen again, please show me the log

2021-08-13 11:56:19 DEBUG (SyncWorker_7) [msmart.command] Finalize request data: aa20ac00000000000003418100ff03ff0002000000000000000000000000135009
2021-08-13 11:56:19 DEBUG (SyncWorker_7) [msmart.device] pkt_builder: 192.168.69.160:192.168.69.160 len: 104 data: 5a5a011168002000000000002c13380b0d08151414040300001100000000000000000000000000006b000a76e27eed2c3647e57d8602df8bc34434dcf8b3d50c422cc227583da33afca5cf91d6d609ef6fbf6e4bfe2e9340440db590d37d782b56118643505e4b5e
2021-08-13 11:56:19 DEBUG (SyncWorker_7) [msmart.lan] Sending to 192.168.69.160:6444 5a5a011168002000000000002c13380b0d08151414040300001100000000000000000000000000006b000a76e27eed2c3647e57d8602df8bc34434dcf8b3d50c422cc227583da33afca5cf91d6d609ef6fbf6e4bfe2e9340440db590d37d782b56118643505e4b5e
2021-08-13 11:56:19 DEBUG (SyncWorker_1) [msmart.command] Finalize request data: aa20ac00000000000003418100ff03ff0002000000000000000000000000135009
2021-08-13 11:56:19 DEBUG (SyncWorker_1) [msmart.device] pkt_builder: 192.168.69.161:192.168.69.161 len: 104 data: 5a5a011168002000000000002c13380b0d08151423910100001d00000000000000000000000000006b000a76e27eed2c3647e57d8602df8bc34434dcf8b3d50c422cc227583da33afca5cf91d6d609ef6fbf6e4bfe2e934052b045855e565311b750170d00cee42d
2021-08-13 11:56:19 DEBUG (SyncWorker_1) [msmart.lan] Attempting new connection to 192.168.69.161:6444
2021-08-13 11:56:19 DEBUG (SyncWorker_1) [msmart.lan] Sending to 192.168.69.161:6444 5a5a011168002000000000002c13380b0d08151423910100001d00000000000000000000000000006b000a76e27eed2c3647e57d8602df8bc34434dcf8b3d50c422cc227583da33afca5cf91d6d609ef6fbf6e4bfe2e934052b045855e565311b750170d00cee42d
2021-08-13 11:56:20 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'consumer_overload' when rendering '{{ value_json.consumer_overload }}'
2021-08-13 11:56:20 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'auto_off' when rendering '{{ value_json.auto_off }}'
2021-08-13 11:56:20 DEBUG (SyncWorker_7) [msmart.lan] Received from 192.168.69.160:6444 5a5a01116800208000000000000000000000000014040300001100000000000000000000010000008936cb5fd894072d294cce7ca7fcfb291672123623be98d1d06041f406edb2a039d328a533c116c0739c684eb4815848785c4fc7809f4173dc717c54d69368e7
2021-08-13 11:56:20 DEBUG (SyncWorker_7) [msmart.lan] Got responses len: 104
2021-08-13 11:56:20 DEBUG (SyncWorker_7) [msmart.device] Got responses from 192.168.69.160:192.168.69.160 Version: 2 Count: 1
2021-08-13 11:56:20 DEBUG (SyncWorker_7) [msmart.device] Update from 192.168.69.160:192.168.69.160 aa22ac00000000000303c00044667f7f0030000000645a00000000000000000009705d
2021-08-13 11:56:20 DEBUG (SyncWorker_7) [msmart.command] Appliance response data: c00044667f7f0030000000645a00000000000000000009705d
2021-08-13 11:56:20 DEBUG (SyncWorker_1) [msmart.lan] Received from 192.168.69.161:6444 5a5a01116800208000000000000000000000000023910100001d0000000000000000000001000000fc341d43f4d3bec6356c9f73a66fde7a2113ae7f7a67f0924772e4128d307b60049fa291d218d1e458398dffcb91e2ff317a83d08cfe8fe651d20465b1650219
2021-08-13 11:56:20 DEBUG (SyncWorker_1) [msmart.lan] Got responses len: 104
2021-08-13 11:56:20 DEBUG (SyncWorker_1) [msmart.device] Got responses from 192.168.69.161:192.168.69.161 Version: 2 Count: 1
2021-08-13 11:56:20 DEBUG (SyncWorker_1) [msmart.device] Update from 192.168.69.161:192.168.69.161 aa22ac00000000000303c00021667f7f00300000006273000000000000000000090ccd
2021-08-13 11:56:20 DEBUG (SyncWorker_1) [msmart.command] Appliance response data: c00021667f7f00300000006273000000000000000000090ccd
2021-08-13 11:56:26 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.RUNNING
2021-08-13 11:56:34 DEBUG (SyncWorker_9) [msmart.command] Finalize request data: aa20ac00000000000003418100ff03ff000200000000000000000000000022b09a
2021-08-13 11:56:34 DEBUG (SyncWorker_9) [msmart.device] pkt_builder: 192.168.69.160:192.168.69.160 len: 104 data: 5a5a011168002000000000002c22380b0d08151414040300001100000000000000000000000000006b000a76e27eed2c3647e57d8602df8bb8fd313676651c24f6a79e1ed661ae4751a1911793778febe1bfc0b33f600e14feac154af276efefb428bd47aabd2885
2021-08-13 11:56:34 DEBUG (SyncWorker_9) [msmart.lan] Sending to 192.168.69.160:6444 5a5a011168002000000000002c22380b0d08151414040300001100000000000000000000000000006b000a76e27eed2c3647e57d8602df8bb8fd313676651c24f6a79e1ed661ae4751a1911793778febe1bfc0b33f600e14feac154af276efefb428bd47aabd2885
2021-08-13 11:56:34 DEBUG (SyncWorker_1) [msmart.command] Finalize request data: aa20ac00000000000003418100ff03ff000200000000000000000000000022b09a
2021-08-13 11:56:34 DEBUG (SyncWorker_1) [msmart.device] pkt_builder: 192.168.69.161:192.168.69.161 len: 104 data: 5a5a011168002000000000002c22380b0d08151423910100001d00000000000000000000000000006b000a76e27eed2c3647e57d8602df8bb8fd313676651c24f6a79e1ed661ae4751a1911793778febe1bfc0b33f600e14006e470015b6d265726bc961dcbc325c
2021-08-13 11:56:34 DEBUG (SyncWorker_1) [msmart.lan] Sending to 192.168.69.161:6444 5a5a011168002000000000002c22380b0d08151423910100001d00000000000000000000000000006b000a76e27eed2c3647e57d8602df8bb8fd313676651c24f6a79e1ed661ae4751a1911793778febe1bfc0b33f600e14006e470015b6d265726bc961dcbc325c
2021-08-13 11:56:35 DEBUG (SyncWorker_1) [msmart.lan] Received from 192.168.69.161:6444 5a5a01116800208000000000000000000000000023910100001d0000000000000000000001000000fc341d43f4d3bec6356c9f73a66fde7a2113ae7f7a67f0924772e4128d307b60a539d4652cd9413a8d99f5fa5302c3e4ab251bac780a6b9adbf51a33bb2acccc
2021-08-13 11:56:35 DEBUG (SyncWorker_1) [msmart.lan] Got responses len: 104
2021-08-13 11:56:35 DEBUG (SyncWorker_1) [msmart.device] Got responses from 192.168.69.161:192.168.69.161 Version: 2 Count: 1
2021-08-13 11:56:35 DEBUG (SyncWorker_1) [msmart.device] Update from 192.168.69.161:192.168.69.161 aa22ac00000000000303c00021667f7f003000000062730000000000000000009aff49
2021-08-13 11:56:35 DEBUG (SyncWorker_1) [msmart.command] Appliance response data: c00021667f7f003000000062730000000000000000009aff49
2021-08-13 11:56:35 DEBUG (SyncWorker_9) [msmart.lan] Received from 192.168.69.160:6444 5a5a01116800208000000000000000000000000014040300001100000000000000000000010000008936cb5fd894072d294cce7ca7fcfb291672123623be98d1d06041f406edb2a0177b7e750c6f4731df18896ea2b2d85559e557cd6151db539874cc451e11116a
2021-08-13 11:56:35 DEBUG (SyncWorker_9) [msmart.lan] Got responses len: 104
2021-08-13 11:56:35 DEBUG (SyncWorker_9) [msmart.device] Got responses from 192.168.69.160:192.168.69.160 Version: 2 Count: 1
2021-08-13 11:56:35 DEBUG (SyncWorker_9) [msmart.device] Update from 192.168.69.160:192.168.69.160 aa22ac00000000000303c00044667f7f0030000000645a0000000000000000009a83b9
2021-08-13 11:56:35 DEBUG (SyncWorker_9) [msmart.command] Appliance response data: c00044667f7f0030000000645a0000000000000000009a83b9

**Comment by mac-zhou** [comment]
@mstefanowicz The log looks okay. the entities is unavailable?

**Comment by mstefanowicz** [comment]
Yes, unavailable.

![obraz](https://user-images.githubusercontent.com/80110715/129341257-1ac87dbb-73a2-4dc7-be09-08cb91bb2052.png)

**Comment by mac-zhou** [comment]
By the way, the device name is different befor.
old may midea_ac_F3A2... but now is midea_ac_18691697869844 and midea_ac_31885837308195

**Comment by mac-zhou** [comment]
https://github.com/mac-zhou/midea-ac-py#attention

**Comment by mstefanowicz** [comment]
@mac-zhou Can you remove my device id from your reply? :)

**Comment by mstefanowicz** [comment]
> By the way, the device name is different befor.

Yes, I changed the id so that it doesn't point to my devices :)

**Comment by mac-zhou** [comment]
> @mac-zhou Can you remove my device id from your reply? :)

done

**Comment by mac-zhou** [comment]
> > By the way, the device name is different befor.
> 
> Yes, I changed the id so that it doesn't point to my devices :)

ok now?

**Comment by mstefanowicz** [comment]
> done

Thx! 
Do you have any suggestions why this doesn't work?

**Comment by mac-zhou** [comment]
> > done
> 
> Thx!
> Do you have any suggestions why this doesn't work?

can you show me midea_ac_<int number>'s status

**Comment by mstefanowicz** [comment]
It's ok, my mistake.
<<< Version> = 0.1.27, the device naming rules have changed. >>>
Sorry for the confusion :)

**Comment by mac-zhou** [comment]
> It's ok, my mistake.
> <<< Version> = 0.1.27, the device naming rules have changed. >>>
> Sorry for the confusion :)

No, my description is not very clear

**Comment by Repsionu** [comment]
I am on latest- but naming change :-( No clue what it means and not available... Could You specifiy what it means?
Best, JR

**Comment by Tjchispas** [comment]
> https://github.com/mac-zhou/midea-ac-py#attention

Any explanation on this would be great

**Comment by pickonedev** [comment]
Same problem here... Climate Unavailable. I use the lastest (0.1.29) and it is not working...

**Comment by pickonedev** [comment]
> 
> 
> > https://github.com/mac-zhou/midea-ac-py#attention
> 
> Any explanation on this would be great

I think he wanted to say that the ENTITY ID of the climate devices has been changed and who have any problem with an entity being "unavailable", they should check whats the name of the new entity and change it in lovlace

**Comment by pickonedev** [comment]
> 
> 
> > It's ok, my mistake.
> > <<< Version> = 0.1.27, the device naming rules have changed. >>>
> > Sorry for the confusion :)
> 
> No, my description is not very clear

I think that the proper description should be:

`The ENTITY ID of the climate devices has been changed and who have any problem with an entity being "unavailable", they should check whats the new ID name of the entity and change it in lovlace`

**Comment by mac-zhou** [comment]
> > > It's ok, my mistake.
> > > <<< Version> = 0.1.27, the device naming rules have changed. >>>
> > > Sorry for the confusion :)
> > 
> > 
> > No, my description is not very clear
> 
> I think that the proper description should be:
> 
> * The ENTITY ID of the climate devices has been changed and who have any problem with an entity being "unavailable", they should check whats the new ID name of the entity and change it in lovlace

thank you
