### ISSUE TITLE
概率出现重启ha后显示不可用

### ISSUE THREAD

**Issue by gmugu** [mac-zhou/midea-ac-py#81]
**Describe the bug （描述一下问题）**
家里4台空调，3台v3，一台v2，都能接入。有一个v3的重启ha后显示不可用，错误日志如下，再次重启ha正常，概率出现

**Screenshots / Logs / Pcap File（屏幕截图/日志/抓包文件）**
If applicable, add screenshots or your home-assistant log file or pcap file to help explain your problem.
请提交相关截图，日志，抓包让开发者能够更快的解决问题

2021-08-14 19:11:49 ERROR (MainThread) [msmart.lan] Couldn't connect with Device 192.168.3.33:6444 [Errno 104] Connection reset by peer
2021-08-14 19:11:49 ERROR (MainThread) [homeassistant.components.climate] Error while setting up midea_ac platform for climate
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
await asyncio.shield(task)
File "/home/homeassistant/.homeassistant/custom_components/midea_ac/climate.py", line 79, in async_setup_platform
device.authenticate(device_k1, device_token)
File "/srv/homeassistant/lib/python3.8/site-packages/msmart/device.py", line 49, in authenticate
self._authenticate()
File "/srv/homeassistant/lib/python3.8/site-packages/msmart/device.py", line 52, in _authenticate
self._lan_service.authenticate(self._token, self._key)
File "/srv/homeassistant/lib/python3.8/site-packages/msmart/lan.py", line 84, in authenticate
raise error
File "/srv/homeassistant/lib/python3.8/site-packages/msmart/lan.py", line 79, in authenticate
tcp_key = self.security.tcp_key(response, self._key)
File "/srv/homeassistant/lib/python3.8/site-packages/msmart/security.py", line 93, in tcp_key
raise Exception('unexpected data length')
Exception: unexpected data length

**Versions (版本信息)**
 - Home Assistant version: 2021.7.4
 - Midea msmart version: 0.1.29

**Comment by mac-zhou** [comment]
可以在配置中添加以下内容，下次再出现问题，请贴出log
```yaml
logger:
  default: info
  logs:
    custom_components.midea_ac: debug
    msmart: debug
```

**Comment by mac-zhou** [comment]
不过其实原因好像也很明显
`Couldn't connect with Device 192.168.3.33:6444 [Errno 104] Connection reset by peer`
不过为何有这个问题，原因暂时不太清楚

**Comment by mac-zhou** [comment]
@gmugu 还出现此问题么？

**Comment by gmugu** [comment]
> @gmugu 还出现此问题么？

最近重启过多次，也没复现出来。
回想一下当时的状态，那一台出现过两次，而且出现的时候都在使用状态，另外3台一次都没出现过，而且当时都处于关闭状态，会不会跟这个有关？

**Comment by mac-zhou** [comment]
怀疑你抓的token和k1， app可能还在使用
当然，还是要避免偶尔连接失败导致直接退出的情况

**Comment by gmugu** [comment]
是，我当时确实正在抓token、k1，app在后台没关

**Comment by mac-zhou** [comment]
升级到 0.1.31 看看问题是否还会出现

**Comment by gmugu** [comment]
> 升级到 0.1.31 看看问题是否还会出现

大神，我最近在出差，回去的时候试试哈
