### ISSUE TITLE
Cannot setup midea_ac platform

### ISSUE THREAD

**Issue by bartlebi** [mac-zhou/midea-ac-py#89]
**Describe the bug （描述一下问题）**
I have 2 midea AC with 3 version.
I setted up it following readme but AC doesn't work.
Midea_discover output:
```
midea-discover -a <log>-p <pass>
INFO:msmart.cli:msmart version: 0.1.33 Currently only supports ac devices.
INFO:msmart.cli:Sending Device Scan Broadcast...
INFO:msmart.lan:Got TCP key for 192.168.88.99:51439 -> 192.168.88.160:6444 retries: 0 time: 0.15866947174072266 7e55768cb60e41ff695ee70d___
INFO:msmart.cli:*** Found a device: ←[94m←[1m{'type': 'ac', 'support': True, 'version': 3, 'ip': '192.168.88.160', 'id': 31885837338569, 'port': 6444, 'token': 'C86E1DEBB8D58814817C7B21DC1D1___', 'key': '396FF1BD568543EAB806611___', 'ssid': 'net_ac_440A'} ←[0m
INFO:msmart.lan:Got TCP key for 192.168.88.99:51441 -> 192.168.88.161:6444 retries: 0 time: 0.5697038173675537 bf0b8420437540cd8c617597669e0___
INFO:msmart.cli:*** Found a device: ←[94m←[1m{'type': 'ac', 'support': True, 'version': 3, 'ip': '192.168.88.161', 'id': 31885837338613, 'port': 6444, 'token': '55274EA9596910DA1D25C74___', 'key': 'C0478F0FD1024FDFA5607787B9C28___', 'ssid': 'net_ac_8F5E'} ←[0m
```

**Screenshots / Logs / Pcap File（屏幕截图/日志/抓包文件）**
If applicable, add screenshots or your home-assistant log file or pcap file to help explain your problem.
请提交相关截图，日志，抓包让开发者能够更快的解决问题
![image](https://user-images.githubusercontent.com/68230970/131184170-948efa83-85e3-4356-83ff-16a81f7659bf.png)
```
Logger: msmart.lan
Source: /usr/local/lib/python3.9/site-packages/msmart/lan.py:42
First occurred: 23:09:30 (72 occurrences)
Last logged: 23:18:19

Connect Error: 192.168.1.160:6444 timed out
Connect Error: 192.168.1.161:6444 timed out
```
```
Logger: msmart.lan
Source: /usr/local/lib/python3.9/site-packages/msmart/lan.py:60
First occurred: 23:09:30 (72 occurrences)
Last logged: 23:18:19

Sokcet is None: 192.168.1.160:6444
Sokcet is None: 192.168.1.161:6444
```
```
Logger: msmart.security
Source: /usr/local/lib/python3.9/site-packages/msmart/security.py:97
First occurred: 23:09:30 (72 occurrences)
Last logged: 23:18:19

unexpected data length
```
```
Logger: homeassistant.helpers.entity
Source: custom_components/midea_ac/climate.py:133
Integration: midea_ac (documentation)
First occurred: 23:09:49 (70 occurrences)
Last logged: 23:18:19

Update for climate.midea_ac_31885837338569 fails
Update for climate.midea_ac_31885837338613 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 446, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in async_device_update
    raise exc
  File "/config/custom_components/midea_ac/climate.py", line 133, in async_update
    await self.hass.async_add_executor_job(self._device.refresh)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/msmart/device.py", line 200, in refresh
    self._send_cmd(cmd)
  File "/usr/local/lib/python3.9/site-packages/msmart/device.py", line 210, in _send_cmd
    responses = self._lan_service.appliance_transparent_send_8370(data)
  File "/usr/local/lib/python3.9/site-packages/msmart/lan.py", line 131, in appliance_transparent_send_8370
    data = self.security.encode_8370(data, msgtype)
  File "/usr/local/lib/python3.9/site-packages/msmart/security.py", line 124, in encode_8370
    data = self.aes_cbc_encrypt(data, self._tcp_key) + sign
  File "/usr/local/lib/python3.9/site-packages/msmart/security.py", line 64, in aes_cbc_encrypt
    return AES.new(key, AES.MODE_CBC, iv=self.iv).encrypt(raw)
  File "/usr/local/lib/python3.9/site-packages/Cryptodome/Cipher/AES.py", line 232, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/Cryptodome/Cipher/__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/Cryptodome/Cipher/_mode_cbc.py", line 274, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "/usr/local/lib/python3.9/site-packages/Cryptodome/Cipher/AES.py", line 92, in _create_base_cipher
    if len(key) not in key_size:
TypeError: object of type 'NoneType' has no len()
```
**Versions (版本信息)**
 - Home Assistant version: core-2021.8.7
 - Midea msmart version: latest

**Comment by mac-zhou** [comment]
Your air conditioner seems to be slow to respond.

https://github.com/mac-zhou/midea-msmart/blob/5e79c6859ec817381e6a093b942f9d7173103720/msmart/lan.py#L35

You can increase the value of `timeout`,  then see if it can be fixed, like:
```python
self._socket.settimeout(4)
```

**Comment by bartlebi** [comment]
Lol. While increasing the timeout and watching the logs, I noticed that the IP address was incorrect - another subnet. Apparently I copied from the example and did not change it to my value  🙈 . The problem was right here! Thank you very much for your work and component, it started working right after the address changes!
