### ISSUE TITLE
Issue with HACS Midea Aircon integration

### ISSUE THREAD

**Issue by kalatos86** [mac-zhou/midea-ac-py#92]
Hi there,

I have problem with integration using custom HACS component Aircon integration.
I have one of the newest HomeAssistant version which is core-2021.8.7.
HACS version is 1.14.1.

My configuration is following:

    platform: midea
    app_key: 3742e9e5842d4ad59c2db887e12449f9
    username: 'xxxx@xxxx.com'
    password: my_midea_password

use_fan_only_workaround: true

The issue is that I am not able to control any Air Conditioner I have. I am still able to control using the Midea app.
The way how the integration is working now is wired. Both devices are automatically switch on in status "Fun_only". Even If I switch them off using Midea app they are started again automatically in "Fun_only" mode,

![obraz](https://user-images.githubusercontent.com/75856476/131268266-6dd7f9c3-103b-4a9a-82b2-9618b73f0d9f.png)

Here is the log I got:

This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/midea/climate.py:119
Integration: midea (documentation)
First occurred: 10:34:48 PM (4 occurrences)
Last logged: 10:41:47 PM

Update for climate.midea_18691697903714 fails
Update for climate.midea_31885837436155 fails
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
six.raise_from(e, None)
File "", line 3, in raise_from
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
httplib_response = conn.getresponse()
File "/usr/local/lib/python3.9/http/client.py", line 1349, in getresponse
response.begin()
File "/usr/local/lib/python3.9/http/client.py", line 316, in begin
version, status, reason = self._read_status()
File "/usr/local/lib/python3.9/http/client.py", line 277, in _read_status
line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
return self._sock.recv_into(b)
File "/usr/local/lib/python3.9/ssl.py", line 1241, in recv_into
return self.read(nbytes, buffer)
File "/usr/local/lib/python3.9/ssl.py", line 1099, in read
return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
resp = conn.urlopen(
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
retries = retries.increment(
File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
raise value
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 447, in _make_request
self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='mapp.appsmb.com', port=443): Read timed out. (read timeout=9)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 446, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in async_device_update
raise exc
File "/config/custom_components/midea/climate.py", line 119, in async_update
await self.hass.async_add_executor_job(self._device.refresh)
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.9/site-packages/midea/device.py", line 146, in refresh
data = self._cloud_service.appliance_transparent_send(self.id, data)
File "/usr/local/lib/python3.9/site-packages/midea/cloud.py", line 171, in appliance_transparent_send
response = self.api_request('appliance/transparent/send', {
File "/usr/local/lib/python3.9/site-packages/midea/cloud.py", line 80, in api_request
r = requests.post(url=url, data=data, timeout=9)
File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 119, in post
return request('post', url, data=data, json=json, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 529, in send
raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='mapp.appsmb.com', port=443): Read timed out. (read timeout=9)

Is anybody has similar issue to the one I have?

**Comment by tmdhx** [comment]
Brother, I thought you have used another platform name midea,but this one named midea_ac.

**Comment by tmdhx** [comment]
Brother, I thought you have used another platform name midea,but this one named midea_ac.

**Comment by mac-zhou** [comment]
it's not my repository
