### ISSUE TITLE
Devices stopped working after few days

### ISSUE THREAD

**Issue by Kazek007** [mac-zhou/midea-ac-py#99]
**Describe the bug （描述一下问题）**
Recently I have configured Midea Smart Aircon for my Kaisai AC and it worked perfectly for several days. Without any changes it stopped working and devices are unavailable. 
When I try to operate thermostat I get the error: "Cannot run the service climate/set_hvac_mode. object of type 'NoneType' has no len()" (sorry, it is my translation to english)

**Screenshots / Logs / Pcap File（屏幕截图/日志/抓包文件）**
```
Logger: homeassistant.helpers.entity
Source: custom_components/midea_ac/climate.py:133
Integration: midea_ac (documentation)
First occurred: 15:55:48 (221 occurrences)
Last logged: 16:19:03

Update for climate.midea_ac_XXXXXXXXXX fails
Update for climate.midea_ac_XXXXXXXXXX fails
Update for climate.midea_ac_XXXXXXXXXX fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 446, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 641, in async_device_update
    raise exc
  File "/config/custom_components/midea_ac/climate.py", line 133, in async_update
    await self.hass.async_add_executor_job(self._device.refresh)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/msmart/device.py", line 198, in refresh
    self._send_cmd(cmd)
  File "/usr/local/lib/python3.9/site-packages/msmart/device.py", line 208, in _send_cmd
    responses = self._lan_service.appliance_transparent_send_8370(data)
  File "/usr/local/lib/python3.9/site-packages/msmart/lan.py", line 136, in appliance_transparent_send_8370
    data = self.security.encode_8370(data, msgtype)
  File "/usr/local/lib/python3.9/site-packages/msmart/security.py", line 117, in encode_8370
    data = self.aes_cbc_encrypt(data, self._tcp_key) + sign
  File "/usr/local/lib/python3.9/site-packages/msmart/security.py", line 57, in aes_cbc_encrypt
    return AES.new(key, AES.MODE_CBC, iv=self.iv).encrypt(raw)
  File "/usr/local/lib/python3.9/site-packages/Cryptodome/Cipher/AES.py", line 232, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/Cryptodome/Cipher/__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/Cryptodome/Cipher/_mode_cbc.py", line 274, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "/usr/local/lib/python3.9/site-packages/Cryptodome/Cipher/AES.py", line 92, in _create_base_cipher
    if len(key) not in key_size:
TypeError: object of type 'NoneType' has no len()
```

**Versions (版本信息)**
 - Home Assistant version: 2021.9.6
 - Midea msmart version: 0.1.35

**Comment by Kazek007** [comment]
Also, I tried to restore backup from few days back and it didn't helped :/

**Comment by Kazek007** [comment]
OMG, sorry for confussion - it was my network's issue, related with static address. Ticket is solved ;)
